on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  project-directory: ./

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, 'skip-ci') &&
      github.event_name == 'push' &&
      github.repository == "Greenstand/${{ github.event.repository.name }}"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.git-tag }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm clean install
        run: npm ci
        working-directory: ${{ env.project-directory }}

      - name: ESLint
        run: npm run lint
        working-directory: ${{ env.project-directory }}

      - run: npm i -g semantic-release @semantic-release/{git,exec,changelog}

      - run: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Get current version number
        run: echo "VERSION=$(node -p 'require("./package.json").version')" >> $GITHUB_ENV

      - name: Bump version number
        run: npm version ${{ env.VERSION }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump version to v${{ env.VERSION }}"
          git tag v${{ env.VERSION }}
          git push origin main --tags

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: npm clean install
        run: npm ci
        working-directory: ${{ env.project-directory }}

      - name: Jest Unit Tests'
        run: npm test
        working-directory: ${{ env.project-directory }}
